version: '3.8'

services:
  keycloak:
    image: my-keycloak:21.1.1
    container_name: keycloak
    ports:
      - "8090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin