version: '3.8'

services:
  keycloak:
    image: my-keycloak:25.0.2
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin