spring:
  datasource:
    softports:
      url: jdbc:postgresql://localhost:5432/postgres
      username: gestor
      password: RoqM%7YF
      jpa:
        properties:
          #show-sql: true
management:
  info.env.enabled: true
  endpoints.web.exposure.include: '*'
info:
  application:
    ambiente: 'Desenvolvimento'

#logging:
#  level:
#    org.springframework.security: DEBUG

#keycloak:
#  grant_type: client_credentials
#  client_id: inteligencia-fiscal-backend
#  client_secret: EncyG9ra0a7EMq85U8A0u27oDYwdvHxI
#  url-end-point-users: https://10.117.10.70:8443/admin/realms/iafis/users
#  url-token-client-secret: https://10.117.10.70:8443/realms/iafis/protocol/openid-connect/token
#  defaultPassword: Mudar@123
